### ISSUE TITLE
Redundant space?

### ISSUE THREAD

**Issue by ayaka14732** [Rongronggg9/SlashBot#1]
我是 Ayaka～现在的效果是

```
Ayaka 摸 了 Rongrong🍨 | 高萌酸钾
```

但如果是汉字，中间没有空格会比较好？

**Comment by Rongronggg9** [comment]
这是考虑到命令内容不一定都能后加「了」而不改其通顺性，因此有意加上的空格。

<details>
\ Ayaka 可爱 /

**Comment by ayaka14732** [comment]
嗯嗯，是耶

<details>\ Rongrong 可爱 /</details>
